const $ = s => document.querySelector(s);
const store = {hospital:{},doctors:[],contacts:[],groups:[],campaigns:[],media:[],knowledge:[],broadcasts:[]};
const save = () => fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(store)}).catch(()=>toast('Could not save: check the server connection.'));
const escapeHTML = v => String(v || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast = message => { const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800) };
const empty = (message, action, label) => `<div class="empty-state" style="grid-column:1/-1;display:flex;flex-direction:column;gap:12px">${message}${action?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`;

function init(){
  document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
  document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));
  $('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop') closeModal()};
  $('#doctorSearch').oninput=renderDoctors; $('#doctorStatus').onchange=renderDoctors;
  $('#hospitalForm').onsubmit=saveHospital;
  renderAll();
}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); const names={overview:'Good morning, Owner',doctors:'Manage your care team',contacts:'Your patient network',campaigns:'Communication that cares',broadcast:'Reach your patients',media:'Your reusable media',knowledge:'Teach your hospital AI',settings:'Your hospital, your details'};$('#pageTitle').textContent=names[page];$('#breadcrumb').textContent=`WORKSPACE / ${page.toUpperCase()}`;}
function renderAll(){renderCounts();renderDoctors();renderContacts();renderCampaigns();renderMedia();renderKnowledge();renderBroadcasts();renderSettings();}
function renderCounts(){const h=store.hospital.name||'Set up your hospital';$('#hospitalMini').innerHTML=`<span class="avatar hospital-avatar">${store.hospital.name?escapeHTML(h[0]).toUpperCase():'+'}</span><div><strong>${escapeHTML(h)}</strong><small>Owner workspace</small></div>`;$('#doctorCount').textContent=store.doctors.length;$('#contactCount').textContent=store.contacts.length;$('#metricDoctors').textContent=store.doctors.filter(d=>d.status==='active').length;$('#metricContacts').textContent=store.contacts.length;$('#metricCampaigns').textContent=store.campaigns.filter(c=>c.status==='active').length;$('#metricKnowledge').textContent=store.knowledge.length;const done=[!!store.hospital.name,store.doctors.length>0,store.knowledge.length>0];$('#progressText').textContent=`${done.filter(Boolean).length} of 3`;$('#progressBar').style.width=`${done.filter(Boolean).length/3*100}%`;$('#setupRows').innerHTML=['Add hospital details','Create your doctor directory','Give AI helpful knowledge'].map((x,i)=>`<div class="check ${done[i]?'done':''}"><b>${done[i]?'✓':''}</b>${x}</div>`).join('');}
function renderDoctors(){const q=($('#doctorSearch').value||'').toLowerCase(),status=$('#doctorStatus').value;let list=store.doctors.filter(d=>(d.name+' '+d.specialization).toLowerCase().includes(q)&&(status==='all'||d.status===status));$('#doctorList').innerHTML=list.length?list.sort((a,b)=>a.priority-b.priority).map(d=>`<article class="doctor-card"><div class="doctor-top">${d.photo?`<img class="doctor-photo" src="${d.photo}" alt="">`:`<div class="doctor-photo">${escapeHTML(d.name[0]||'D')}</div>`}<div><h3>${escapeHTML(d.name)}</h3><small>${escapeHTML(d.qualification||'Doctor')} · ${escapeHTML(d.specialization||'General')}</small></div><span class="status ${d.status==='disabled'?'disabled':''}">${d.status==='active'?'Active':'Disabled'}</span></div><div class="doctor-info"><span>▣ ${escapeHTML(d.availableDays||'Availability not set')}</span><span>⌂ Room ${escapeHTML(d.room||'—')}</span><span>₹ ${escapeHTML(d.fees||'—')} fee</span><span>⌁ ${escapeHTML(d.languages||'—')}</span></div><div class="doctor-actions"><button class="secondary" onclick="editDoctor('${d.id}')">Edit</button><button class="secondary" onclick="toggleDoctor('${d.id}')">${d.status==='active'?'Disable':'Enable'}</button><button class="text-button danger" onclick="deleteDoctor('${d.id}')">Delete</button></div></article>`).join(''):empty('No doctors yet. Add profiles so your AI knows who is available.','doctor','+ Add doctor');}
function renderContacts(){const valid=store.contacts.filter(c=>c.valid).length;$('#totalContacts').textContent=store.contacts.length;$('#groupCount').textContent=store.groups.length;$('#validPhones').textContent=valid;$('#groupList').innerHTML=store.groups.length?store.groups.map(g=>`<span class="group-chip">${escapeHTML(g)} <button onclick="deleteGroup('${escapeHTML(g)}')">×</button></span>`).join(''):'<span style="font-size:12px;color:#829198">No groups yet — create one to segment patients.</span>';$('#contactTable').innerHTML=store.contacts.length?`<table><thead><tr><th>NAME</th><th>PHONE</th><th>EMAIL</th><th>COMPANY</th><th>GROUPS</th></tr></thead><tbody>${store.contacts.slice(0,10).map(c=>`<tr><td>${escapeHTML(c.name)}</td><td>${escapeHTML(c.phone)} ${c.valid?'✓':'⚠'}</td><td>${escapeHTML(c.email||'—')}</td><td>${escapeHTML(c.company||'—')}</td><td>${escapeHTML(c.group||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-message">No contacts imported yet.</div>';}
function renderCampaigns(){$('#campaignList').innerHTML=store.campaigns.length?store.campaigns.map(c=>`<article class="campaign-card"><span class="status ${c.status==='active'?'':'disabled'}">${c.status==='active'?'Scheduled':'Draft'}</span><h3>${escapeHTML(c.name)}</h3><span class="campaign-type">${escapeHTML(c.type)}</span><p>${escapeHTML(c.message)}</p><footer>To: ${escapeHTML(c.audience)} · ${escapeHTML(c.schedule)}</footer></article>`).join(''):empty('No campaigns created yet. Schedule helpful follow-ups for your patients.','campaign','+ Create campaign');}
function renderMedia(){$('#mediaList').innerHTML=store.media.length?store.media.map(m=>`<article class="media-card"><div class="media-preview">${m.type.startsWith('image')?'▧':m.type.includes('video')?'▶':'▤'}</div><strong>${escapeHTML(m.name)}</strong><small>${escapeHTML(m.type)}</small></article>`).join(''):empty('Your library is empty. Upload doctor photos, logos, PDFs, reports, and videos.','media','⇧ Upload media');}
function renderKnowledge(){$('#knowledgeList').innerHTML=store.knowledge.length?store.knowledge.map(k=>`<div class="knowledge-item"><b>▤</b><span>${escapeHTML(k.name)}<small>${escapeHTML(k.type)} · Ready for AI answers</small></span><button class="text-button danger" onclick="deleteKnowledge('${k.id}')">Remove</button></div>`).join(''):empty('No knowledge added yet. Upload your first file to teach your AI.','knowledge','⇧ Add knowledge');}
function renderBroadcasts(){const audiences=['All patients','Selected patients','Selected groups','Visited a specific doctor','Specific disease','Haven’t visited for X days','Follow-up is due'];$('#audienceOptions').innerHTML=audiences.map((a,i)=>`<label class="audience-option"><input type="radio" name="audience" value="${a}" ${i===0?'checked':''}>${a}</label>`).join('');$('#broadcastLogs').innerHTML=store.broadcasts.length?store.broadcasts.map(b=>`<div class="knowledge-item"><b style="color:#249478">✓</b><span>${escapeHTML(b.message)}<small>${escapeHTML(b.audience)} · ${b.total} recipients · ${b.date}</small></span><span class="status">${b.success} sent</span></div>`).join(''):'<div class="empty-message">No broadcast activity yet.</div>';}
function renderSettings(){Object.entries(store.hospital).forEach(([k,v])=>{const el=$(`#hospitalForm [name="${k}"]`);if(el&&k!=='logo')el.value=v});}
function openModal(content){$('#modal').innerHTML=content;$('#modalBackdrop').classList.add('open')}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
function openAction(action){if(action==='doctor')return doctorModal();if(action==='contacts')return contactsModal();if(action==='campaign')return campaignModal();if(action==='media')return uploadModal('media');if(action==='knowledge')return uploadModal('knowledge');if(action==='group')return groupModal();if(action==='broadcast')return broadcastModal();}
const field=(name,label,type='text',value='',wide=false,placeholder='')=>`<label class="${wide?'wide':''}">${label}<input name="${name}" type="${type}" value="${escapeHTML(value)}" placeholder="${placeholder}" /></label>`;
function doctorModal(data={}){openModal(`<div class="modal-head"><h2>${data.id?'Edit':'Add'} doctor</h2><button onclick="closeModal()">×</button></div><p>Complete profiles help the AI give correct doctor and appointment answers.</p><form id="doctorForm"><div class="form-grid">${field('name','Full name','text',data.name,'','Dr. full name')}${field('qualification','Qualification','text',data.qualification)}${field('specialization','Specialization','text',data.specialization)}${field('experience','Experience','text',data.experience,'','e.g. 12 years')}${field('registration','Registration number','text',data.registration)}${field('fees','Consultation fees','number',data.fees)}${field('languages','Languages spoken','text',data.languages,'','Hindi, English')}${field('availableDays','Available days','text',data.availableDays,'','Mon–Sat')}${field('slots','Available time slots','text',data.slots,'','10:00 AM–2:00 PM')}${field('breakTime','Break time','text',data.breakTime)}${field('holidays','Holiday schedule','text',data.holidays)}${field('room','Room number','text',data.room)}${field('phone','Phone number','tel',data.phone)}${field('whatsapp','WhatsApp number','tel',data.whatsapp)}${field('email','Email','email',data.email)}${field('priority','Priority order','number',data.priority||store.doctors.length+1)}<label class="wide">Short bio<textarea name="bio">${escapeHTML(data.bio||'')}</textarea></label><label class="wide">Long description<textarea name="description">${escapeHTML(data.description||'')}</textarea></label><label>Profile photo<input name="photo" type="file" accept="image/*" /></label><label>Status<select name="status"><option value="active" ${data.status!=='disabled'?'selected':''}>Active</option><option value="disabled" ${data.status==='disabled'?'selected':''}>Disabled</option></select></label></div><div class="modal-footer"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save doctor</button></div></form>`);$('#doctorForm').onsubmit=e=>saveDoctor(e,data.id);}
function saveDoctor(e,id){e.preventDefault();const f=new FormData(e.target),d=Object.fromEntries(f.entries());d.id=id||crypto.randomUUID();const photo=f.get('photo');if(photo&&photo.size){const r=new FileReader();r.onload=()=>{d.photo=r.result;finishDoctor(d,id)};r.readAsDataURL(photo)}else{d.photo=(store.doctors.find(x=>x.id===id)||{}).photo||'';finishDoctor(d,id)}}
function finishDoctor(d,id){id?store.doctors.splice(store.doctors.findIndex(x=>x.id===id),1,d):store.doctors.push(d);save();closeModal();renderAll();toast('Doctor profile saved. AI will use these details.');}
function contactsModal(){openModal(`<div class="modal-head"><h2>Import patient contacts</h2><button onclick="closeModal()">×</button></div><p>Upload a VCF, CSV, Excel file, or Google Contacts export. Duplicates are removed by phone number.</p><div class="dropzone">▧<br><label>Choose a contact file<input id="contactFile" type="file" accept=".vcf,.csv,.xlsx,.xls,text/vcard,text/csv"></label><br><small>VCF · CSV · XLSX · Google Contacts CSV</small></div><div id="previewArea"></div><div class="modal-footer"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="confirmImport" disabled>Import contacts</button></div>`);$('#contactFile').onchange=previewContacts;}
function parseContacts(text,name){if(name.toLowerCase().endsWith('.vcf'))return text.split(/END:VCARD/i).map(v=>({name:(v.match(/FN:(.*)/i)||[])[1]||'',phone:(v.match(/TEL[^:]*:(.*)/i)||[])[1]||'',email:(v.match(/EMAIL[^:]*:(.*)/i)||[])[1]||'',company:(v.match(/ORG:(.*)/i)||[])[1]||'',notes:(v.match(/NOTE:(.*)/i)||[])[1]||''})).filter(c=>c.name||c.phone);let lines=text.split(/\r?\n/).filter(Boolean),heads=(lines.shift()||'').split(',').map(x=>x.trim().toLowerCase());return lines.map(l=>{let a=l.split(',').map(x=>x.trim()),get=(...keys)=>a[heads.findIndex(h=>keys.some(k=>h.includes(k)))]||'';return{name:get('name','first'),phone:get('phone','mobile'),email:get('email'),company:get('company','organization'),notes:get('note')}}).filter(c=>c.name||c.phone)}
async function previewContacts(e){const file=e.target.files[0];if(!file)return;const data=new FormData();data.append('file',file);$('#previewArea').innerHTML='<div class="import-preview">Reading and validating contacts…</div>';try{const r=await fetch('/api/contacts/preview',{method:'POST',body:data}),out=await r.json();if(!r.ok)throw Error(out.error);window.previewedContacts=out.contacts;$('#previewArea').innerHTML=`<div class="import-preview"><strong>${out.contacts.length} unique contacts ready to import</strong><table><tr><th>Name</th><th>Phone</th><th>Email</th></tr>${out.contacts.slice(0,5).map(c=>`<tr><td>${escapeHTML(c.name)}</td><td>${escapeHTML(c.phone)} ${c.valid?'✓':'⚠'}</td><td>${escapeHTML(c.email)}</td></tr>`).join('')}</table></div>`;$('#confirmImport').disabled=false;$('#confirmImport').onclick=async()=>{const r=await fetch('/api/contacts/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contacts:window.previewedContacts})}),out=await r.json();if(!r.ok)return toast(out.error||'Import failed');store.contacts.push(...out.contacts);closeModal();renderAll();toast(`${out.added} contacts imported, deduplicated, and validated.`)}}catch(err){$('#previewArea').innerHTML=`<div class="import-preview">${escapeHTML(err.message)}</div>`;toast('Could not preview this file.')}}
function groupModal(){openModal(`<div class="modal-head"><h2>Create contact group</h2><button onclick="closeModal()">×</button></div><form id="groupForm"><label>Group name<input name="name" placeholder="e.g. Diabetes patients" required></label><div class="modal-footer"><button class="secondary" type="button" onclick="closeModal()">Cancel</button><button class="primary">Create group</button></div></form>`);$('#groupForm').onsubmit=e=>{e.preventDefault();let n=new FormData(e.target).get('name').trim();if(n&&!store.groups.includes(n)){store.groups.push(n);save();renderAll();toast('Contact group created.')}closeModal()}}
function campaignModal(){const types=['Appointment Reminder','Medicine Reminder','Health Tips','Vaccination Reminder','Festival Greetings','Recovery Follow-up','Health Checkup Reminder','Custom Message'];openModal(`<div class="modal-head"><h2>Create campaign</h2><button onclick="closeModal()">×</button></div><form id="campaignForm"><div class="form-grid">${field('name','Campaign name','text','','','e.g. Monsoon health tips')}<label>Campaign type<select name="type">${types.map(t=>`<option>${t}</option>`).join('')}</select></label><label>Audience<select name="audience"><option>All Patients</option>${store.groups.map(g=>`<option>Group: ${escapeHTML(g)}</option>`).join('')}</select></label>${field('schedule','Send schedule','text','','','e.g. Every Monday, 10:00 AM')}<label class="wide">Message (use {{patient_name}}, {{doctor_name}}, {{appointment_date}}, {{disease}}, {{language}})<textarea name="message" required placeholder="Write a caring, useful message..."></textarea></label><label>Attach image, logo, PDF, or document<input type="file" name="attachment"></label><label>Status<select name="status"><option value="active">Schedule campaign</option><option value="draft">Save as draft</option></select></label></div><div class="modal-footer"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save campaign</button></div></form>`);$('#campaignForm').onsubmit=e=>{e.preventDefault();let c=Object.fromEntries(new FormData(e.target).entries());c.id=crypto.randomUUID();store.campaigns.push(c);save();closeModal();renderAll();toast('Campaign saved and ready to schedule.')}}
function uploadModal(kind){const isK=kind==='knowledge',title=isK?'Add AI knowledge':'Upload media';openModal(`<div class="modal-head"><h2>${title}</h2><button onclick="closeModal()">×</button></div><p>${isK?'Your AI will use these files when replying to patients.':'Files can be reused in campaigns and AI conversations.'}</p><div class="dropzone">⇧<br><label>Choose file<input id="uploadFile" type="file" accept="${isK?'.pdf,.docx,.txt':'image/*,video/*,.pdf,.doc,.docx'}"></label><br><small>${isK?'PDF · DOCX · TXT':'Doctor photos · Logos · Images · PDFs · Reports · Videos'}</small></div><div class="modal-footer"><button class="secondary" onclick="closeModal()">Cancel</button><button id="saveUpload" class="primary" disabled>Save file</button></div>`);$('#uploadFile').onchange=e=>{$('#saveUpload').disabled=!e.target.files[0]};$('#saveUpload').onclick=async()=>{let f=$('#uploadFile').files[0];if(!f)return;const fd=new FormData();fd.append('file',f);$('#saveUpload').disabled=true;const r=await fetch(`/api/files/${kind}`,{method:'POST',body:fd}),item=await r.json();if(!r.ok){$('#saveUpload').disabled=false;return toast(item.error||'Upload failed')}store[isK?'knowledge':'media'].push(item);closeModal();renderAll();toast(isK?'Knowledge added. AI can now use it.':'Media saved to your library.')}}
function broadcastModal(){openModal(`<div class="modal-head"><h2>New broadcast</h2><button onclick="closeModal()">×</button></div><form id="broadcastForm"><label>Audience<select name="audience"><option>All patients</option><option>Selected patients</option>${store.groups.map(g=>`<option>Group: ${escapeHTML(g)}</option>`).join('')}</select></label><label style="display:block;margin-top:14px">WATI approved template name<input name="templateName" required placeholder="e.g. appointment_reminder"></label><label style="display:block;margin-top:14px">Broadcast name<input name="broadcastName" required placeholder="e.g. July appointment reminders"></label><label style="display:block;margin-top:14px">Internal message note<textarea name="message" required placeholder="This appears in your dashboard; WATI sends the approved template."></textarea></label><p>For patient safety and WhatsApp compliance, WATI broadcasts use an approved template.</p><div class="modal-footer"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Send broadcast</button></div></form>`);$('#broadcastForm').onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target).entries());const r=await fetch('/api/broadcasts/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)}),out=await r.json();if(!r.ok)return toast(out.error||'Broadcast failed');store.broadcasts.unshift(out);closeModal();renderAll();toast(`${out.success} sent; ${out.failed} failed. Check delivery logs.`)}}
function saveHospital(e){e.preventDefault();store.hospital={...store.hospital,...Object.fromEntries(new FormData(e.target).entries())};delete store.hospital.logo;save();renderAll();toast('Hospital settings saved.');}
window.closeModal=closeModal;window.editDoctor=id=>doctorModal(store.doctors.find(d=>d.id===id));window.toggleDoctor=id=>{let d=store.doctors.find(d=>d.id===id);d.status=d.status==='active'?'disabled':'active';save();renderAll();toast(`Doctor ${d.status==='active'?'enabled':'disabled'}.`)};window.deleteDoctor=id=>{if(confirm('Delete this doctor profile?')){store.doctors=store.doctors.filter(d=>d.id!==id);save();renderAll();toast('Doctor deleted.')}};window.deleteGroup=name=>{store.groups=store.groups.filter(g=>g!==name);save();renderAll()};window.deleteKnowledge=id=>{store.knowledge=store.knowledge.filter(k=>k.id!==id);save();renderAll();toast('Knowledge file removed.');};fetch('/api/state').then(r=>r.json()).then(data=>Object.assign(store,data)).catch(()=>toast('Server not connected. Start it with npm start.')).finally(init);
