require('dotenv').config();
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const express = require('express');
const multer = require('multer');
const cron = require('node-cron');
const XLSX = require('xlsx');
const mammoth = require('mammoth');
const pdf = require('pdf-parse');
const Groq = require('groq-sdk');
const QRCode = require('qrcode');
const { DatabaseSync } = require('node:sqlite');

const app = express();
const port = process.env.PORT || 3000;
const root = __dirname;
const dataDir = path.join(root, 'data');
const uploadDir = path.join(root, 'uploads');
fs.mkdirSync(dataDir, { recursive: true }); fs.mkdirSync(uploadDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'vardan.sqlite'));
db.exec(`CREATE TABLE IF NOT EXISTS state (id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS files (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT, category TEXT NOT NULL, path TEXT NOT NULL, extracted_text TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries (id TEXT PRIMARY KEY, campaign_id TEXT, recipient TEXT, status TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS whatsapp_sessions (phone TEXT PRIMARY KEY, step TEXT NOT NULL, language TEXT, patient_name TEXT, data TEXT, updated_at TEXT NOT NULL);`);
const emptyState = { hospital:{}, doctors:[], contacts:[], groups:[], campaigns:[], media:[], knowledge:[], broadcasts:[], appointments:[] };
const waWeb = { socket:null, status:'disconnected', qr:null, error:null, starting:false };
function getState(){ const row=db.prepare('SELECT payload FROM state WHERE id=1').get(); return row ? JSON.parse(row.payload) : structuredClone(emptyState); }
function putState(body){ const payload=JSON.stringify({ ...emptyState, ...body }); db.prepare('INSERT INTO state(id,payload,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').run(payload,new Date().toISOString()); return JSON.parse(payload); }
function id(){ return crypto.randomUUID(); }
function getSession(phone){return db.prepare('SELECT * FROM whatsapp_sessions WHERE phone=?').get(phone)||{phone,step:'language',language:'',patient_name:'',data:'{}'};}
function setSession(s){db.prepare('INSERT INTO whatsapp_sessions(phone,step,language,patient_name,data,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(phone) DO UPDATE SET step=excluded.step,language=excluded.language,patient_name=excluded.patient_name,data=excluded.data,updated_at=excluded.updated_at').run(s.phone,s.step,s.language||'',s.patient_name||'',s.data||'{}',new Date().toISOString());}
function words(language){return language==='hi'?{welcome:'नमस्ते! VARDAN Hospital Assistant में आपका स्वागत है।\n\nकृपया भाषा चुनें:\n1. हिंदी\n2. English',name:'कृपया अपना पूरा नाम लिखें।',registered:'धन्यवाद, {name}! आपका registration पूरा हो गया।\n\nआप क्या करना चाहते हैं?\n1. Appointment book करें\n2. Hospital / doctor information लें\n\nकभी भी MENU लिखकर यह menu देख सकते हैं।',menu:'आप क्या करना चाहते हैं?\n1. Appointment book करें\n2. Hospital / doctor information लें',doctor:'Doctor चुनें—उसका number भेजें:',time:'कृपया अपनी preferred date और time लिखें। उदाहरण: 20 July, 11 AM',confirmed:'आपका appointment request दर्ज हो गया है। हमारी टीम शीघ्र confirm करेगी।\n\nMENU लिखकर फिर से options देखें।',askInfo:'अपना सवाल लिखें। MENU लिखकर वापस options देखें।',unknown:'कृपया 1 या 2 लिखकर option चुनें।'}:{welcome:'Welcome to VARDAN Hospital Assistant.\n\nPlease choose your language:\n1. हिंदी\n2. English',name:'Please enter your full name.',registered:'Thank you, {name}! Your registration is complete.\n\nWhat would you like to do?\n1. Book an appointment\n2. Get hospital / doctor information\n\nType MENU anytime to see these options.',menu:'What would you like to do?\n1. Book an appointment\n2. Get hospital / doctor information',doctor:'Choose a doctor—send their number:',time:'Please share your preferred date and time. Example: 20 July, 11 AM',confirmed:'Your appointment request has been recorded. Our team will confirm it shortly.\n\nType MENU to see options again.',askInfo:'Type your question. Type MENU to return to options.',unknown:'Please reply with 1 or 2.'};}
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(_,f,cb)=>cb(null,`${Date.now()}-${crypto.randomUUID()}${path.extname(f.originalname)}`)}),limits:{fileSize:20*1024*1024}});
app.use(express.json({limit:'15mb'})); app.use('/uploads',express.static(uploadDir)); app.use(express.static(root));
app.get('/api/health',(_,res)=>res.json({ok:true,service:'VARDAN.ai',integrations:{groq:!!process.env.GROQ_API_KEY,whatsapp:!!(process.env.WHATSAPP_WEB_ENABLED==='true'||(process.env.WATI_API_ENDPOINT&&process.env.WATI_API_TOKEN&&process.env.WATI_CHANNEL_NUMBER)||(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID)),whatsappProvider:process.env.WHATSAPP_WEB_ENABLED==='true'?'WhatsApp Web':process.env.WATI_API_TOKEN?'WATI':process.env.WHATSAPP_TOKEN?'Meta Cloud API':'not configured',sheets:!!process.env.GOOGLE_SHEETS_WEBHOOK_URL}}));
app.get('/api/state',(_,res)=>res.json(getState()));
app.put('/api/state',(req,res)=>res.json(putState(req.body)));

function normalizePhone(v=''){return String(v).replace(/[^\d+]/g,'');}
function contactFromRow(row={}){ const get=(...keys)=>{const k=Object.keys(row).find(x=>keys.some(key=>x.toLowerCase().includes(key)));return k?String(row[k]||''):''}; const phone=normalizePhone(get('phone','mobile','tel','number')); return {id:id(),name:get('name','first','full name'),phone,email:get('email'),company:get('company','organization','org'),notes:get('note','comment'),valid:/^\+?\d{7,15}$/.test(phone)}; }
function parseVcf(text){return text.split(/END:VCARD/i).map(v=>({name:(v.match(/(?:FN):(.+)/i)||[])[1]||'',phone:(v.match(/TEL[^:]*:(.+)/i)||[])[1]||'',email:(v.match(/EMAIL[^:]*:(.+)/i)||[])[1]||'',company:(v.match(/ORG:(.+)/i)||[])[1]||'',notes:(v.match(/NOTE:(.+)/i)||[])[1]||''})).filter(c=>c.name||c.phone).map(c=>({...c,id:id(),phone:normalizePhone(c.phone),valid:/^\+?\d{7,15}$/.test(normalizePhone(c.phone))}));}
app.post('/api/contacts/preview',upload.single('file'),(req,res)=>{try{const f=req.file;if(!f)return res.status(400).json({error:'A file is required'});let rows=[];if(/\.vcf$/i.test(f.originalname))rows=parseVcf(fs.readFileSync(f.path,'utf8'));else {const wb=XLSX.readFile(f.path);rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}).map(contactFromRow);}fs.unlinkSync(f.path);const seen=new Set();rows=rows.filter(c=>{const key=c.phone||`${c.name}|${c.email}`;if(seen.has(key))return false;seen.add(key);return key.trim();});res.json({contacts:rows});}catch(e){res.status(400).json({error:`Could not read contacts: ${e.message}`})}});
app.post('/api/contacts/import',(req,res)=>{const state=getState();const known=new Set(state.contacts.map(c=>normalizePhone(c.phone)));const added=(req.body.contacts||[]).filter(c=>{const p=normalizePhone(c.phone);if(!p||known.has(p))return false;known.add(p);return true;}).map(c=>({...c,id:c.id||id(),phone:normalizePhone(c.phone),valid:/^\+?\d{7,15}$/.test(normalizePhone(c.phone))}));state.contacts.push(...added);putState(state);mirrorContacts(added).catch(console.error);res.json({added:added.length,contacts:added});});
async function mirrorContacts(contacts){if(!process.env.GOOGLE_SHEETS_WEBHOOK_URL||!contacts.length)return;await fetch(process.env.GOOGLE_SHEETS_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contacts})});}

async function extractText(file){if(/\.txt$/i.test(file.originalname))return fs.readFileSync(file.path,'utf8');if(/\.docx$/i.test(file.originalname))return (await mammoth.extractRawText({path:file.path})).value;if(/\.pdf$/i.test(file.originalname))return (await pdf(fs.readFileSync(file.path))).text;return '';}
app.post('/api/files/:category',upload.single('file'),async(req,res)=>{try{const category=req.params.category;if(!['media','knowledge'].includes(category)||!req.file)return res.status(400).json({error:'Choose a media or knowledge file'});const item={id:id(),name:req.file.originalname,type:req.file.mimetype||path.extname(req.file.originalname),category,path:`/uploads/${req.file.filename}`,createdAt:new Date().toISOString()};const extracted=category==='knowledge'?await extractText(req.file):'';db.prepare('INSERT INTO files VALUES(?,?,?,?,?,?,?)').run(item.id,item.name,item.type,item.category,item.path,extracted,item.createdAt);const state=getState();state[category].push(item);putState(state);res.json(item);}catch(e){res.status(400).json({error:`Upload failed: ${e.message}`})}});

async function startWhatsAppWeb(){
  if(process.env.WHATSAPP_WEB_ENABLED!=='true')throw new Error('Set WHATSAPP_WEB_ENABLED=true in .env, then restart the server.');
  if(waWeb.starting||waWeb.status==='connected')return;
  waWeb.starting=true;waWeb.error=null;waWeb.status='connecting';
  try{
    const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion}=await import('@whiskeysockets/baileys');
    const pino=(await import('pino')).default;
    const {state,saveCreds}=await useMultiFileAuthState(path.join(dataDir,'whatsapp-web-session'));
    const {version}=await fetchLatestBaileysVersion();
    const socket=makeWASocket({version,auth:state,printQRInTerminal:false,logger:pino({level:'silent'}),browser:['VARDAN.ai','Chrome','1.0.0']});waWeb.socket=socket;
    socket.ev.on('creds.update',saveCreds);
    socket.ev.on('messages.upsert',async({messages,type})=>{if(type!=='notify')return;for(const message of messages){try{if(message.key.fromMe||!message.message)continue;const text=message.message.conversation||message.message.extendedTextMessage?.text||message.message.buttonsResponseMessage?.selectedDisplayText||message.message.listResponseMessage?.title||'';if(text.trim())await handleIncomingWhatsApp(socket,message.key.remoteJid,text.trim());}catch(e){console.error('WhatsApp inbound flow error:',e.message)}}});
    socket.ev.on('connection.update',async({connection,lastDisconnect,qr})=>{if(qr)waWeb.qr=await QRCode.toDataURL(qr);if(connection==='open'){waWeb.status='connected';waWeb.qr=null;waWeb.starting=false;}if(connection==='close'){waWeb.socket=null;waWeb.starting=false;const code=lastDisconnect?.error?.output?.statusCode;if(code===DisconnectReason.loggedOut){waWeb.status='logged_out';waWeb.qr=null;}else{waWeb.status='disconnected';setTimeout(()=>startWhatsAppWeb().catch(e=>waWeb.error=e.message),2500);}}});
  }catch(e){waWeb.status='error';waWeb.error=e.message;waWeb.starting=false;throw e;}
}
app.get('/api/whatsapp-web/status',(_,res)=>res.json({enabled:process.env.WHATSAPP_WEB_ENABLED==='true',status:waWeb.status,qr:waWeb.qr,error:waWeb.error}));
app.post('/api/whatsapp-web/connect',async(_,res)=>{try{await startWhatsAppWeb();res.json({status:waWeb.status,qr:waWeb.qr});}catch(e){res.status(400).json({error:e.message})}});
async function sendWhatsApp(phone,text,templateName,broadcastName){
  if(process.env.WHATSAPP_WEB_ENABLED==='true'){if(waWeb.status!=='connected'||!waWeb.socket)throw new Error('Scan the WhatsApp Web QR in Hospital Settings before sending.');return waWeb.socket.sendMessage(`${phone.replace(/\D/g,'')}@s.whatsapp.net`,{text});}
  if(process.env.WATI_API_ENDPOINT&&process.env.WATI_API_TOKEN&&process.env.WATI_CHANNEL_NUMBER){
    if(!templateName)throw new Error('Choose a WATI-approved template before sending.');
    const base=process.env.WATI_API_ENDPOINT.replace(/\/$/,'');
    const r=await fetch(`${base}/api/v1/sendTemplateMessages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WATI_API_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({receivers:[{whatsappNumber:phone.replace(/^\+/,'')}],template_name:templateName,broadcast_name:broadcastName||'VARDAN broadcast',channel_number:process.env.WATI_CHANNEL_NUMBER})});
    if(!r.ok)throw new Error(`WATI: ${await r.text()}`);return r.json();
  }
  if(!process.env.WHATSAPP_TOKEN||!process.env.WHATSAPP_PHONE_NUMBER_ID)throw new Error('Configure WATI or WhatsApp Cloud API in .env.');
  const r=await fetch(`https://graph.facebook.com/v20.0/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WHATSAPP_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:phone.replace(/^\+/,''),type:'text',text:{body:text}})});if(!r.ok)throw new Error(await r.text());return r.json();
}
async function answerKnowledge(question){if(!process.env.GROQ_API_KEY)return 'The hospital owner has not added AI knowledge yet. Please contact the hospital directly.';const state=getState(),docs=db.prepare("SELECT name,extracted_text FROM files WHERE category='knowledge' ORDER BY created_at DESC").all().map(x=>`SOURCE: ${x.name}\n${x.extracted_text||''}`).join('\n\n').slice(0,24000),doctors=state.doctors.map(d=>`${d.name}: ${d.specialization}; ${d.availableDays}; ${d.slots}; fees ${d.fees}`).join('\n');const groq=new Groq({apiKey:process.env.GROQ_API_KEY});const out=await groq.chat.completions.create({model:process.env.GROQ_MODEL||'llama-3.3-70b-versatile',messages:[{role:'system',content:`You are the hospital's patient assistant. Only use provided hospital context. If unavailable, say the owner has not added this information. Never diagnose or prescribe. Doctors:\n${doctors}\n\nKnowledge:\n${docs}`},{role:'user',content:question}],temperature:.2,max_tokens:700});return out.choices[0].message.content;}
async function handleIncomingWhatsApp(socket,jid,text){
  const phone=jid.split('@')[0].replace(/\D/g,'');if(!phone)return;let s=getSession(phone),state=getState(),clean=text.trim(),lower=clean.toLowerCase();
  if(['hi','hello','hii','start','menu','नमस्ते','हाय'].includes(lower)||!s.step){s={phone,step:'language',language:'',patient_name:'',data:'{}'};setSession(s);return socket.sendMessage(jid,{text:words('en').welcome});}
  if(s.step==='language'){if(['1','hindi','हिंदी'].includes(lower))s.language='hi';else if(['2','english','eng'].includes(lower))s.language='en';else return socket.sendMessage(jid,{text:words('en').welcome});s.step='name';setSession(s);return socket.sendMessage(jid,{text:words(s.language).name});}
  const t=words(s.language||'en');
  if(s.step==='name'){s.patient_name=clean;s.step='menu';setSession(s);const existing=state.contacts.find(c=>c.phone.replace(/\D/g,'')===phone);if(!existing){state.contacts.push({id:id(),name:clean,phone:`+${phone}`,email:'',company:'',notes:'Registered through WhatsApp',valid:true});putState(state);}return socket.sendMessage(jid,{text:t.registered.replace('{name}',clean)});}
  if(s.step==='menu'){if(lower==='1'||lower.includes('appointment')||lower.includes('अपॉइंटमेंट')){const doctors=state.doctors.filter(d=>d.status==='active');if(!doctors.length)return socket.sendMessage(jid,{text:s.language==='hi'?'अभी कोई doctor उपलब्ध नहीं है। कृपया hospital को call करें।':'No doctor is currently available. Please call the hospital.'});s.step='doctor';s.data=JSON.stringify({doctorIds:doctors.map(d=>d.id)});setSession(s);return socket.sendMessage(jid,{text:`${t.doctor}\n\n${doctors.map((d,i)=>`${i+1}. Dr. ${d.name.replace(/^Dr\.\s*/i,'')} — ${d.specialization||''}`).join('\n')}`});}if(lower==='2'||lower.includes('info')||lower.includes('information')||lower.includes('जानकारी')){s.step='info';setSession(s);return socket.sendMessage(jid,{text:t.askInfo});}return socket.sendMessage(jid,{text:t.unknown});}
  if(s.step==='doctor'){const ids=JSON.parse(s.data||'{}').doctorIds||[],doctor=state.doctors.find(d=>d.id===ids[Number(clean)-1]);if(!doctor)return socket.sendMessage(jid,{text:t.doctor});s.step='appointment_time';s.data=JSON.stringify({doctorId:doctor.id});setSession(s);return socket.sendMessage(jid,{text:`Dr. ${doctor.name.replace(/^Dr\.\s*/i,'')}\n${doctor.availableDays||''} ${doctor.slots||''}\n\n${t.time}`});}
  if(s.step==='appointment_time'){const doctor=state.doctors.find(d=>d.id===JSON.parse(s.data||'{}').doctorId);state.appointments.push({id:id(),patientName:s.patient_name,phone:`+${phone}`,doctorId:doctor?.id||'',doctorName:doctor?.name||'',requestedTime:clean,status:'pending',createdAt:new Date().toISOString()});putState(state);s.step='menu';setSession(s);return socket.sendMessage(jid,{text:t.confirmed});}
  if(s.step==='info'){if(lower==='menu'){s.step='menu';setSession(s);return socket.sendMessage(jid,{text:t.menu});}try{return socket.sendMessage(jid,{text:await answerKnowledge(clean)});}catch(e){return socket.sendMessage(jid,{text:s.language==='hi'?'अभी जानकारी उपलब्ध नहीं है। कृपया बाद में कोशिश करें।':'Information is unavailable right now. Please try again later.'});}}
}
function personalized(text,contact,doctor={}){return text.replace(/{{\s*patient_name\s*}}/gi,contact.name||'Patient').replace(/{{\s*doctor_name\s*}}/gi,doctor.name||'Doctor').replace(/{{\s*language\s*}}/gi,contact.language||'English');}
app.post('/api/broadcasts/send',async(req,res)=>{const state=getState(),{message,audience='All patients',templateName,broadcastName}=req.body;let recipients=state.contacts;if(audience.startsWith('Group:'))recipients=recipients.filter(c=>c.group===audience.slice(7));const results=[];for(const c of recipients.filter(c=>c.valid)){try{await sendWhatsApp(c.phone,personalized(message,c),templateName,broadcastName);results.push({recipient:c.phone,status:'sent'});}catch(e){results.push({recipient:c.phone,status:'failed',error:e.message});} }for(const r of results)db.prepare('INSERT INTO deliveries VALUES(?,?,?,?,?,?)').run(id(),null,r.recipient,r.status,r.error||null,new Date().toISOString());const log={id:id(),message,audience,total:recipients.length,success:results.filter(r=>r.status==='sent').length,failed:results.filter(r=>r.status==='failed').length,date:new Date().toLocaleDateString()};state.broadcasts.unshift(log);putState(state);res.json(log);});
app.get('/api/deliveries',(_,res)=>res.json(db.prepare('SELECT * FROM deliveries ORDER BY created_at DESC LIMIT 200').all()));
app.post('/api/ai/ask',async(req,res)=>{if(!process.env.GROQ_API_KEY)return res.status(503).json({error:'Add GROQ_API_KEY to .env to activate AI.'});const question=String(req.body.question||'').slice(0,4000),state=getState();const docs=db.prepare("SELECT name,extracted_text FROM files WHERE category='knowledge' ORDER BY created_at DESC").all().map(x=>`SOURCE: ${x.name}\n${x.extracted_text||''}`).join('\n\n').slice(0,24000);const doctors=state.doctors.map(d=>`${d.name}: ${d.specialization}; ${d.availableDays}; ${d.slots}; fees ${d.fees}`).join('\n');try{const groq=new Groq({apiKey:process.env.GROQ_API_KEY});const out=await groq.chat.completions.create({model:process.env.GROQ_MODEL||'llama-3.3-70b-versatile',messages:[{role:'system',content:`You are the hospital's patient assistant. Only use provided hospital context. If unavailable, say the owner has not added this information. Never diagnose or prescribe. Doctors:\n${doctors}\n\nKnowledge:\n${docs}`},{role:'user',content:question}],temperature:.2,max_tokens:700});res.json({answer:out.choices[0].message.content});}catch(e){res.status(502).json({error:`AI request failed: ${e.message}`})}});
// Checks scheduled campaigns each minute. Configure a cron expression in a campaign's scheduleCron field.
cron.schedule('* * * * *',()=>{const state=getState();state.campaigns.filter(c=>c.status==='active'&&c.scheduleCron).forEach(c=>{if(cron.validate(c.scheduleCron)&&cron.schedule(c.scheduleCron,()=>console.log(`Campaign ${c.name} due`),{scheduled:false})) console.log(`Campaign ${c.name} schedule validated`);});});
app.get('/{*splat}',(_,res)=>res.sendFile(path.join(root,'index.html')));
app.listen(port,()=>console.log(`VARDAN.ai running at http://localhost:${port}`));
