require('dotenv').config();
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const express = require('express');
const multer = require('multer');
const cron = require('node-cron');
const XLSX = require('xlsx');
const mammoth = require('mammoth');
const pdf = require('pdf-parse');
const Groq = require('groq-sdk');
const QRCode = require('qrcode');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const cookieParser = require('cookie-parser');
const { DatabaseSync } = require('node:sqlite');

const app = express();
const port = process.env.PORT || 3000;
const root = __dirname;
const dataDir = path.join(root, 'data');
const uploadDir = path.join(root, 'uploads');
fs.mkdirSync(dataDir, { recursive: true }); fs.mkdirSync(uploadDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'vardan.sqlite'));
db.exec(`CREATE TABLE IF NOT EXISTS state (id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS files (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT, category TEXT NOT NULL, path TEXT NOT NULL, extracted_text TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries (id TEXT PRIMARY KEY, campaign_id TEXT, recipient TEXT, status TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS whatsapp_sessions (phone TEXT PRIMARY KEY, step TEXT NOT NULL, language TEXT, patient_name TEXT, data TEXT, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS whatsapp_messages (id TEXT PRIMARY KEY, phone TEXT NOT NULL, direction TEXT NOT NULL, text TEXT NOT NULL, created_at TEXT NOT NULL);`);
const emptyState = { hospital:{}, doctors:[], contacts:[], groups:[], campaigns:[], media:[], knowledge:[], broadcasts:[], appointments:[] };
const waWeb = { socket:null, status:'disconnected', qr:null, error:null, starting:false };
const adminEmail = process.env.ADMIN_EMAIL || '';
const adminPasswordHash = bcrypt.hashSync(process.env.ADMIN_PASSWORD || crypto.randomUUID(), 12);
const jwtSecret = process.env.JWT_SECRET || crypto.randomUUID();
function getState(){ const row=db.prepare('SELECT payload FROM state WHERE id=1').get(); return row ? JSON.parse(row.payload) : structuredClone(emptyState); }
function putState(body){ const payload=JSON.stringify({ ...emptyState, ...body }); db.prepare('INSERT INTO state(id,payload,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').run(payload,new Date().toISOString()); return JSON.parse(payload); }
function id(){ return crypto.randomUUID(); }
function getSession(phone){return db.prepare('SELECT * FROM whatsapp_sessions WHERE phone=?').get(phone)||{phone,step:'language',language:'',patient_name:'',data:'{}'};}
function setSession(s){db.prepare('INSERT INTO whatsapp_sessions(phone,step,language,patient_name,data,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(phone) DO UPDATE SET step=excluded.step,language=excluded.language,patient_name=excluded.patient_name,data=excluded.data,updated_at=excluded.updated_at').run(s.phone,s.step,s.language||'',s.patient_name||'',s.data||'{}',new Date().toISOString());}
function logWhatsAppMessage(phone,direction,text){if(!text)return;db.prepare('INSERT INTO whatsapp_messages VALUES(?,?,?,?,?)').run(id(),phone,direction,text,new Date().toISOString());}
function words(language){return language==='hi'?{welcome:'नमस्ते! VARDAN Hospital Assistant में आपका स्वागत है।\n\nकृपया भाषा चुनें:\n1. हिंदी\n2. English',name:'कृपया एक ही message में अपनी details भेजें:\n\nनाम: Rahul Sharma\nउम्र / age: 12\nmobile number: +919876543210\ngender: male',age:'कृपया अपनी उम्र लिखें।',mobile:'कृपया अपना mobile number country code के साथ लिखें। उदाहरण: +919876543210',gender:'कृपया अपना gender लिखें। उदाहरण: Male / Female / Other',registered:'धन्यवाद, {name}! आपका registration पूरा हो गया।\n\nआप क्या करना चाहते हैं?\n1. Appointment book करें\n2. Hospital / doctor information लें\n\nकभी भी MENU लिखकर यह menu देख सकते हैं।',menu:'आप क्या करना चाहते हैं?\n1. Appointment book करें\n2. Hospital / doctor information लें',doctor:'Doctor चुनें—उसका number भेजें:',time:'आप जैसे भी लिखना चाहें, appointment time भेजें। उदाहरण: कल 11 बजे, Monday morning, 20 July, या बस “कल”. हमारी टीम जरूरत पड़े तो confirm करेगी।',confirmed:'आपका appointment request दर्ज हो गया है। हमारी टीम शीघ्र confirm करेगी।\n\nMENU लिखकर फिर से options देखें।',askInfo:'अपना सवाल लिखें। MENU लिखकर वापस options देखें।',unknown:'कृपया 1 या 2 लिखकर option चुनें।'}:{welcome:'Welcome to VARDAN Hospital Assistant.\n\nPlease choose your language:\n1. हिंदी\n2. English',name:'Please send all details in one message:\n\nName: Rahul Sharma\nAge: 12\nMobile number: +919876543210\nGender: male',age:'Please enter your age.',mobile:'Please enter your mobile number with country code. Example: +919876543210',gender:'Please enter your gender. Example: Male / Female / Other',registered:'Thank you, {name}! Your registration is complete.\n\nWhat would you like to do?\n1. Book an appointment\n2. Get hospital / doctor information\n\nType MENU anytime to see these options.',menu:'What would you like to do?\n1. Book an appointment\n2. Get hospital / doctor information',doctor:'Choose a doctor—send their number:',time:'Send your appointment time in any way you like. Examples: tomorrow 11 AM, Monday morning, 20 July, or simply “tomorrow”. Our team will confirm if needed.',confirmed:'Your appointment request has been recorded. Our team will confirm it shortly.\n\nType MENU to see options again.',askInfo:'Type your question. Type MENU to return to options.',unknown:'Please reply with 1 or 2.'};}
function savePatientRegistration(state,s,phone,details){const existing=state.contacts.find(c=>c.phone.replace(/\D/g,'')===(details.mobile||phone).replace(/\D/g,''));const patient={id:id(),name:s.patient_name,phone:details.mobile||`+${phone}`,age:details.age,gender:details.gender,email:'',company:'',notes:'Registered through WhatsApp',valid:true};if(existing)Object.assign(existing,patient,{id:existing.id});else state.contacts.push(patient);putState(state);}
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(_,f,cb)=>cb(null,`${Date.now()}-${crypto.randomUUID()}${path.extname(f.originalname)}`)}),limits:{fileSize:20*1024*1024}});
function authGuard(req,res,next){try{const token=req.cookies?.vardan_admin;if(!token)throw Error('Missing login');req.user=jwt.verify(token,jwtSecret);next();}catch{if(req.path.startsWith('/api/'))return res.status(401).json({error:'Login required'});res.redirect('/login.html');}}
app.use(express.json({limit:'15mb'}));app.use(cookieParser());
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{};if(email!==adminEmail||!bcrypt.compareSync(String(password||''),adminPasswordHash))return res.status(401).json({error:'Incorrect email or password'});const token=jwt.sign({email},jwtSecret,{expiresIn:'12h'});res.cookie('vardan_admin',token,{httpOnly:true,sameSite:'lax',secure:false,maxAge:12*60*60*1000});res.json({ok:true,email});});
app.post('/api/auth/logout',(_,res)=>{res.clearCookie('vardan_admin');res.json({ok:true})});
app.get('/api/auth/session',(req,res)=>{try{res.json({authenticated:true,email:jwt.verify(req.cookies?.vardan_admin||'',jwtSecret).email})}catch{res.json({authenticated:false})}});
app.use('/api',(req,res,next)=>req.path==='/health'?next():authGuard(req,res,next));
app.use('/uploads',authGuard,express.static(uploadDir));app.get('/index.html',authGuard,(_,res)=>res.sendFile(path.join(root,'index.html')));app.use(express.static(root,{index:false}));
app.get('/api/health',(_,res)=>res.json({ok:true,service:'VARDAN.ai',integrations:{groq:!!process.env.GROQ_API_KEY,whatsapp:!!(process.env.WHATSAPP_WEB_ENABLED==='true'||(process.env.WATI_API_ENDPOINT&&process.env.WATI_API_TOKEN&&process.env.WATI_CHANNEL_NUMBER)||(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID)),whatsappProvider:process.env.WHATSAPP_WEB_ENABLED==='true'?'WhatsApp Web':process.env.WATI_API_TOKEN?'WATI':process.env.WHATSAPP_TOKEN?'Meta Cloud API':'not configured',sheets:!!process.env.GOOGLE_SHEETS_WEBHOOK_URL}}));
app.get('/api/state',(_,res)=>res.json(getState()));
app.put('/api/state',(req,res)=>{const previous=getState(),next={...previous,...req.body};for(const key of ['contacts','appointments']){const records=new Map((previous[key]||[]).map(item=>[item.id,item]));for(const item of (req.body[key]||[]))records.set(item.id,item);next[key]=[...records.values()];}res.json(putState(next));});
app.get('/api/chats',(_,res)=>res.json(db.prepare('SELECT phone, MAX(created_at) AS lastAt, (SELECT text FROM whatsapp_messages m2 WHERE m2.phone=m1.phone ORDER BY created_at DESC LIMIT 1) AS preview FROM whatsapp_messages m1 GROUP BY phone ORDER BY lastAt DESC').all()));
app.get('/api/chats/:phone',(req,res)=>res.json(db.prepare('SELECT * FROM whatsapp_messages WHERE phone=? ORDER BY created_at ASC').all(req.params.phone)));

function normalizePhone(v=''){return String(v).replace(/[^\d+]/g,'');}
function contactFromRow(row={}){ const get=(...keys)=>{const k=Object.keys(row).find(x=>keys.some(key=>x.toLowerCase().includes(key)));return k?String(row[k]||''):''}; const phone=normalizePhone(get('phone','mobile','tel','number')); return {id:id(),name:get('name','first','full name'),phone,email:get('email'),company:get('company','organization','org'),notes:get('note','comment'),valid:/^\+?\d{7,15}$/.test(phone)}; }
function parseVcf(text){return text.split(/END:VCARD/i).map(v=>({name:(v.match(/(?:FN):(.+)/i)||[])[1]||'',phone:(v.match(/TEL[^:]*:(.+)/i)||[])[1]||'',email:(v.match(/EMAIL[^:]*:(.+)/i)||[])[1]||'',company:(v.match(/ORG:(.+)/i)||[])[1]||'',notes:(v.match(/NOTE:(.+)/i)||[])[1]||''})).filter(c=>c.name||c.phone).map(c=>({...c,id:id(),phone:normalizePhone(c.phone),valid:/^\+?\d{7,15}$/.test(normalizePhone(c.phone))}));}
app.post('/api/contacts/preview',upload.single('file'),(req,res)=>{let f;try{f=req.file;if(!f)return res.status(400).json({error:'A file is required'});let rows=[];if(/\.(?:vcf|vfc)$/i.test(f.originalname))rows=parseVcf(fs.readFileSync(f.path,'utf8'));else {const wb=XLSX.readFile(f.path);rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}).map(contactFromRow);}const seen=new Set();rows=rows.filter(c=>{const key=c.phone||`${c.name}|${c.email}`;if(seen.has(key))return false;seen.add(key);return key.trim();});res.json({contacts:rows});}catch(e){res.status(400).json({error:`Could not read contacts: ${e.message}`})}finally{if(f?.path)fs.rmSync(f.path,{force:true})}});
app.post('/api/contacts/import',(req,res)=>{const state=getState();const known=new Set(state.contacts.map(c=>normalizePhone(c.phone)));const added=(req.body.contacts||[]).filter(c=>{const p=normalizePhone(c.phone);if(!p||known.has(p))return false;known.add(p);return true;}).map(c=>({...c,id:c.id||id(),phone:normalizePhone(c.phone),valid:/^\+?\d{7,15}$/.test(normalizePhone(c.phone))}));state.contacts.push(...added);putState(state);syncToSheets(state,'patients',added).catch(console.error);res.json({added:added.length,contacts:added});});
async function syncToSheets(state,type,records){const url=process.env.GOOGLE_SHEETS_WEBHOOK_URL||state.hospital?.googleSheetsWebhook;if(!url||!records?.length)return;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,records,source:'VARDAN.ai'})});if(!r.ok)throw new Error(`Google Sheets returned ${r.status}`);}

async function extractText(file){if(/\.txt$/i.test(file.originalname))return fs.readFileSync(file.path,'utf8');if(/\.docx$/i.test(file.originalname))return (await mammoth.extractRawText({path:file.path})).value;if(/\.pdf$/i.test(file.originalname))return (await pdf(fs.readFileSync(file.path))).text;return '';}
app.post('/api/files/:category',upload.single('file'),async(req,res)=>{try{const category=req.params.category;if(!['media','knowledge'].includes(category)||!req.file)return res.status(400).json({error:'Choose a media or knowledge file'});const item={id:id(),name:req.file.originalname,type:req.file.mimetype||path.extname(req.file.originalname),category,path:`/uploads/${req.file.filename}`,createdAt:new Date().toISOString()};const extracted=category==='knowledge'?await extractText(req.file):'';db.prepare('INSERT INTO files VALUES(?,?,?,?,?,?,?)').run(item.id,item.name,item.type,item.category,item.path,extracted,item.createdAt);const state=getState();state[category].push(item);putState(state);res.json(item);}catch(e){res.status(400).json({error:`Upload failed: ${e.message}`})}});

async function startWhatsAppWeb(){
  if(process.env.WHATSAPP_WEB_ENABLED!=='true')throw new Error('Set WHATSAPP_WEB_ENABLED=true in .env, then restart the server.');
  if(waWeb.starting||waWeb.status==='connected')return;
  waWeb.starting=true;waWeb.error=null;waWeb.status='connecting';
  try{
    const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion}=await import('@whiskeysockets/baileys');
    const pino=(await import('pino')).default;
    const {state,saveCreds}=await useMultiFileAuthState(path.join(dataDir,'whatsapp-web-session'));
    const {version}=await fetchLatestBaileysVersion();
    const socket=makeWASocket({version,auth:state,printQRInTerminal:false,logger:pino({level:'silent'}),browser:['VARDAN.ai','Chrome','1.0.0']});waWeb.socket=socket;
    socket.ev.on('creds.update',saveCreds);
    socket.ev.on('messages.upsert',async({messages,type})=>{if(type!=='notify')return;for(const message of messages){try{if(!message.message)continue;const text=message.message.conversation||message.message.extendedTextMessage?.text||message.message.buttonsResponseMessage?.selectedDisplayText||message.message.listResponseMessage?.title||'';const phone=message.key.remoteJid?.split('@')[0]?.replace(/\D/g,'');if(text.trim()&&phone)logWhatsAppMessage(phone,message.key.fromMe?'outgoing':'incoming',text.trim());if(message.key.fromMe||!text.trim())continue;await handleIncomingWhatsApp(socket,message.key.remoteJid,text.trim());}catch(e){console.error('WhatsApp inbound flow error:',e.message)}}});
    socket.ev.on('connection.update',async({connection,lastDisconnect,qr})=>{if(qr)waWeb.qr=await QRCode.toDataURL(qr);if(connection==='open'){waWeb.status='connected';waWeb.qr=null;waWeb.starting=false;}if(connection==='close'){waWeb.socket=null;waWeb.starting=false;const code=lastDisconnect?.error?.output?.statusCode;if(code===DisconnectReason.loggedOut){waWeb.status='logged_out';waWeb.qr=null;}else{waWeb.status='disconnected';setTimeout(()=>startWhatsAppWeb().catch(e=>waWeb.error=e.message),2500);}}});
  }catch(e){waWeb.status='error';waWeb.error=e.message;waWeb.starting=false;throw e;}
}
app.get('/api/whatsapp-web/status',(_,res)=>res.json({enabled:process.env.WHATSAPP_WEB_ENABLED==='true',status:waWeb.status,qr:waWeb.qr,error:waWeb.error}));
app.post('/api/whatsapp-web/connect',async(_,res)=>{try{await startWhatsAppWeb();res.json({status:waWeb.status,qr:waWeb.qr});}catch(e){res.status(400).json({error:e.message})}});
async function sendWhatsApp(phone,text,templateName,broadcastName){
  if(process.env.WHATSAPP_WEB_ENABLED==='true'){if(waWeb.status!=='connected'||!waWeb.socket)throw new Error('Scan the WhatsApp Web QR in Hospital Settings before sending.');return waWeb.socket.sendMessage(`${phone.replace(/\D/g,'')}@s.whatsapp.net`,{text});}
  if(process.env.WATI_API_ENDPOINT&&process.env.WATI_API_TOKEN&&process.env.WATI_CHANNEL_NUMBER){
    if(!templateName)throw new Error('Choose a WATI-approved template before sending.');
    const base=process.env.WATI_API_ENDPOINT.replace(/\/$/,'');
    const r=await fetch(`${base}/api/v1/sendTemplateMessages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WATI_API_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({receivers:[{whatsappNumber:phone.replace(/^\+/,'')}],template_name:templateName,broadcast_name:broadcastName||'VARDAN broadcast',channel_number:process.env.WATI_CHANNEL_NUMBER})});
    if(!r.ok)throw new Error(`WATI: ${await r.text()}`);return r.json();
  }
  if(!process.env.WHATSAPP_TOKEN||!process.env.WHATSAPP_PHONE_NUMBER_ID)throw new Error('Configure WATI or WhatsApp Cloud API in .env.');
  const r=await fetch(`https://graph.facebook.com/v20.0/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WHATSAPP_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:phone.replace(/^\+/,''),type:'text',text:{body:text}})});if(!r.ok)throw new Error(await r.text());return r.json();
}
async function answerKnowledge(question){if(!process.env.GROQ_API_KEY)return 'The hospital owner has not added AI knowledge yet. Please contact the hospital directly.';const state=getState(),docs=db.prepare("SELECT name,extracted_text FROM files WHERE category='knowledge' ORDER BY created_at DESC").all().map(x=>`SOURCE: ${x.name}\n${x.extracted_text||''}`).join('\n\n').slice(0,24000),doctors=state.doctors.map(d=>`${d.name}: ${d.specialization}; ${d.availableDays}; ${d.slots}; fees ${d.fees}`).join('\n');const groq=new Groq({apiKey:process.env.GROQ_API_KEY});const out=await groq.chat.completions.create({model:process.env.GROQ_MODEL||'llama-3.3-70b-versatile',messages:[{role:'system',content:`You are the hospital's patient assistant. Only use provided hospital context. If unavailable, say the owner has not added this information. Never diagnose or prescribe. Doctors:\n${doctors}\n\nKnowledge:\n${docs}`},{role:'user',content:question}],temperature:.2,max_tokens:700});return out.choices[0].message.content;}
function dateTimeKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;}
function dateTimeLabel(date,language){return new Intl.DateTimeFormat(language==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'long',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true}).format(date);}
function parseFlexibleDateTime(requested){const text=requested.toLowerCase(),now=new Date();let date=new Date(now);if(/\b(tomorrow|kal)\b|कल/.test(text))date.setDate(date.getDate()+1);else if(/\b(day after tomorrow|parso)\b|परसों/.test(text))date.setDate(date.getDate()+2);else {const native=new Date(requested);if(!Number.isNaN(native.getTime()))date=native;else {const dayMatch=text.match(/\b(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/);if(dayMatch){const target=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'].indexOf(dayMatch[1]);date.setDate(date.getDate()+((target-date.getDay()+7)%7||7));}else return null;}}const time=text.match(/(?:at\s*)?(\d{1,2})(?::(\d{2}))?\s*(am|pm|a\.m\.|p\.m\.|बजे|baje)?/i);if(!time)return null;let hour=Number(time[1]),minute=Number(time[2]||0),tag=(time[3]||'').toLowerCase();if((tag==='pm'||tag==='p.m.')&&hour<12)hour+=12;if((tag==='am'||tag==='a.m.')&&hour===12)hour=0;if(hour>23||minute>59)return null;date.setHours(hour,minute,0,0);return date;}
function appointmentSuggestion(state,doctor,requested){const parsed=parseFlexibleDateTime(requested);if(!parsed)return null;let candidate=parsed,days=(doctor.availableDays||'').toLowerCase(),tries=0;while(tries++<21){const day=candidate.toLocaleDateString('en-US',{weekday:'long'}).toLowerCase();const unavailable=days&&days!=='all days'&&!days.includes(day)&&!days.includes(day.slice(0,3));const taken=state.appointments.some(a=>a.doctorId===doctor.id&&a.timeKey===dateTimeKey(candidate)&&a.status!=='cancelled');if(!unavailable&&!taken)return {date:candidate,key:dateTimeKey(candidate),changed:dateTimeKey(parsed)!==dateTimeKey(candidate)};candidate=new Date(candidate.getTime()+86400000);}return null;}
async function handleIncomingWhatsApp(socket,jid,text){
  const phone=jid.split('@')[0].replace(/\D/g,'');if(!phone)return;let s=getSession(phone),state=getState(),clean=text.trim(),lower=clean.toLowerCase();
  if(['hi','hello','hii','start','menu','नमस्ते','हाय'].includes(lower)||!s.step){s={phone,step:'language',language:'',patient_name:'',data:'{}'};setSession(s);return socket.sendMessage(jid,{text:words('en').welcome});}
  if(s.step==='language'){if(['1','hindi','हिंदी'].includes(lower))s.language='hi';else if(['2','english','eng'].includes(lower))s.language='en';else return socket.sendMessage(jid,{text:words('en').welcome});s.step='name';setSession(s);return socket.sendMessage(jid,{text:words(s.language).name});}
  const t=words(s.language||'en');
  if(s.step==='name'){const ageMatch=clean.match(/(?:age|उम्र)\s*[:=-]?\s*(\d{1,3})/i),mobileMatch=clean.match(/(?:mobile(?:\s*number)?|phone|मोबाइल)\s*[:=-]?\s*(\+?\d[\d\s-]{6,})/i),genderMatch=clean.match(/(?:gender|लिंग)\s*[:=-]?\s*([^\r\n]+)/i),nameMatch=clean.match(/(?:name|नाम)\s*[:=-]?\s*([^\r\n]+)/i);if(ageMatch&&mobileMatch&&genderMatch){s.patient_name=(nameMatch?.[1]||clean.split(/\r?\n/).find(line=>line.trim()&&!/:/.test(line))||'Patient').trim();const details={age:Number(ageMatch[1]),mobile:normalizePhone(mobileMatch[1]),gender:genderMatch[1].trim()};s.data=JSON.stringify(details);s.step='menu';setSession(s);savePatientRegistration(state,s,phone,details);syncToSheets(state,'patients',[{name:s.patient_name,phone:details.mobile,age:details.age,gender:details.gender}]).catch(console.error);return socket.sendMessage(jid,{text:t.registered.replace('{name}',s.patient_name)});}return socket.sendMessage(jid,{text:t.name});}
  if(s.step==='age'){if(!/^\d{1,3}$/.test(clean)||Number(clean)>130)return socket.sendMessage(jid,{text:t.age});s.step='mobile';s.data=JSON.stringify({...JSON.parse(s.data||'{}'),age:Number(clean)});setSession(s);return socket.sendMessage(jid,{text:t.mobile});}
  if(s.step==='mobile'){const mobile=normalizePhone(clean);if(!/^\+?\d{7,15}$/.test(mobile))return socket.sendMessage(jid,{text:t.mobile});s.step='gender';s.data=JSON.stringify({...JSON.parse(s.data||'{}'),mobile});setSession(s);return socket.sendMessage(jid,{text:t.gender});}
  if(s.step==='gender'){const details={...JSON.parse(s.data||'{}'),gender:clean};s.data=JSON.stringify(details);s.step='menu';setSession(s);savePatientRegistration(state,s,phone,details);syncToSheets(state,'patients',[{name:s.patient_name,phone:details.mobile||`+${phone}`,age:details.age,gender:details.gender}]).catch(console.error);return socket.sendMessage(jid,{text:t.registered.replace('{name}',s.patient_name)});}
  if(s.step==='menu'){if(lower==='1'||lower.includes('appointment')||lower.includes('अपॉइंटमेंट')){const doctors=state.doctors.filter(d=>d.status==='active');if(!doctors.length)return socket.sendMessage(jid,{text:s.language==='hi'?'अभी कोई doctor उपलब्ध नहीं है। कृपया hospital को call करें।':'No doctor is currently available. Please call the hospital.'});s.step='doctor';s.data=JSON.stringify({doctorIds:doctors.map(d=>d.id)});setSession(s);return socket.sendMessage(jid,{text:`${t.doctor}\n\n${doctors.map((d,i)=>`${i+1}. Dr. ${d.name.replace(/^Dr\.\s*/i,'')} — ${d.specialization||''}`).join('\n')}`});}if(lower==='2'||lower.includes('info')||lower.includes('information')||lower.includes('जानकारी')){s.step='info';setSession(s);return socket.sendMessage(jid,{text:t.askInfo});}return socket.sendMessage(jid,{text:t.unknown});}
  if(s.step==='doctor'){const ids=JSON.parse(s.data||'{}').doctorIds||[],doctor=state.doctors.find(d=>d.id===ids[Number(clean)-1]);if(!doctor)return socket.sendMessage(jid,{text:t.doctor});s.step='appointment_time';s.data=JSON.stringify({doctorId:doctor.id});setSession(s);return socket.sendMessage(jid,{text:`Dr. ${doctor.name.replace(/^Dr\.\s*/i,'')}\n${doctor.availableDays||''} ${doctor.slots||''}\n\n${t.time}`});}
  if(s.step==='appointment_time'){const doctor=state.doctors.find(d=>d.id===JSON.parse(s.data||'{}').doctorId),slot=doctor&&appointmentSuggestion(state,doctor,clean);if(!slot)return socket.sendMessage(jid,{text:s.language==='hi'?'मैं आपकी मदद करूँगा। कृपया दिन और लगभग time फिर से लिखें—जैसे “कल 11 बजे”, “Monday सुबह”, या “20 July 2 PM”.':'I will help you book it. Please tell me the day and approximate time—for example “tomorrow 11 AM”, “Monday morning”, or “20 July 2 PM”.'});const appointment={id:id(),patientName:s.patient_name,phone:`+${phone}`,doctorId:doctor.id,doctorName:doctor.name,requestedTime:clean,scheduledTime:dateTimeLabel(slot.date,s.language),timeKey:slot.key,status:'pending',createdAt:new Date().toISOString()};if(slot.changed){s.step='appointment_confirm';s.data=JSON.stringify({appointment});setSession(s);return socket.sendMessage(jid,{text:s.language==='hi'?`यह समय available नहीं है। हम ${appointment.scheduledTime} recommend करते हैं।\n\nConfirm करने के लिए YES लिखें या नया date/time लिखें।`:`This time is unavailable. We recommend ${appointment.scheduledTime}.\n\nReply YES to confirm, or send another date/time.`});}state.appointments.push(appointment);putState(state);syncToSheets(state,'appointments',[appointment]).catch(console.error);s.step='menu';setSession(s);return socket.sendMessage(jid,{text:t.confirmed});}
  if(s.step==='appointment_confirm'){const pending=JSON.parse(s.data||'{}').appointment;if(lower==='yes'||lower==='haan'||lower==='ha'){state.appointments.push(pending);putState(state);syncToSheets(state,'appointments',[pending]).catch(console.error);s.step='menu';setSession(s);return socket.sendMessage(jid,{text:t.confirmed});}s.step='appointment_time';setSession(s);return handleIncomingWhatsApp(socket,jid,clean);}
  if(s.step==='info'){if(lower==='menu'){s.step='menu';setSession(s);return socket.sendMessage(jid,{text:t.menu});}try{return socket.sendMessage(jid,{text:await answerKnowledge(clean)});}catch(e){return socket.sendMessage(jid,{text:s.language==='hi'?'अभी जानकारी उपलब्ध नहीं है। कृपया बाद में कोशिश करें।':'Information is unavailable right now. Please try again later.'});}}
}
function personalized(text,contact,doctor={}){return text.replace(/{{\s*patient_name\s*}}/gi,contact.name||'Patient').replace(/{{\s*doctor_name\s*}}/gi,doctor.name||'Doctor').replace(/{{\s*language\s*}}/gi,contact.language||'English');}
app.post('/api/broadcasts/send',async(req,res)=>{const state=getState(),{message,audience='All patients',templateName,broadcastName}=req.body;let recipients=state.contacts;if(audience.startsWith('Group:'))recipients=recipients.filter(c=>c.group===audience.slice(7));const results=[];for(const c of recipients.filter(c=>c.valid)){try{await sendWhatsApp(c.phone,personalized(message,c),templateName,broadcastName);results.push({recipient:c.phone,status:'sent'});}catch(e){results.push({recipient:c.phone,status:'failed',error:e.message});} }for(const r of results)db.prepare('INSERT INTO deliveries VALUES(?,?,?,?,?,?)').run(id(),null,r.recipient,r.status,r.error||null,new Date().toISOString());const log={id:id(),message,audience,total:recipients.length,success:results.filter(r=>r.status==='sent').length,failed:results.filter(r=>r.status==='failed').length,date:new Date().toLocaleDateString()};state.broadcasts.unshift(log);putState(state);res.json(log);});
app.get('/api/deliveries',(_,res)=>res.json(db.prepare('SELECT * FROM deliveries ORDER BY created_at DESC LIMIT 200').all()));
app.post('/api/ai/ask',async(req,res)=>{if(!process.env.GROQ_API_KEY)return res.status(503).json({error:'Add GROQ_API_KEY to .env to activate AI.'});const question=String(req.body.question||'').slice(0,4000),state=getState();const docs=db.prepare("SELECT name,extracted_text FROM files WHERE category='knowledge' ORDER BY created_at DESC").all().map(x=>`SOURCE: ${x.name}\n${x.extracted_text||''}`).join('\n\n').slice(0,24000);const doctors=state.doctors.map(d=>`${d.name}: ${d.specialization}; ${d.availableDays}; ${d.slots}; fees ${d.fees}`).join('\n');try{const groq=new Groq({apiKey:process.env.GROQ_API_KEY});const out=await groq.chat.completions.create({model:process.env.GROQ_MODEL||'llama-3.3-70b-versatile',messages:[{role:'system',content:`You are the hospital's patient assistant. Only use provided hospital context. If unavailable, say the owner has not added this information. Never diagnose or prescribe. Doctors:\n${doctors}\n\nKnowledge:\n${docs}`},{role:'user',content:question}],temperature:.2,max_tokens:700});res.json({answer:out.choices[0].message.content});}catch(e){res.status(502).json({error:`AI request failed: ${e.message}`})}});
// Checks scheduled campaigns each minute. Configure a cron expression in a campaign's scheduleCron field.
cron.schedule('* * * * *',()=>{const state=getState();state.campaigns.filter(c=>c.status==='active'&&c.scheduleCron).forEach(c=>{if(cron.validate(c.scheduleCron)&&cron.schedule(c.scheduleCron,()=>console.log(`Campaign ${c.name} due`),{scheduled:false})) console.log(`Campaign ${c.name} schedule validated`);});});
app.get('/',authGuard,(_,res)=>res.sendFile(path.join(root,'index.html')));
app.get('/{*splat}',authGuard,(_,res)=>res.sendFile(path.join(root,'index.html')));
app.listen(port,()=>{console.log(`VARDAN.ai running at http://localhost:${port}`);if(process.env.WHATSAPP_WEB_ENABLED==='true')startWhatsAppWeb().catch(e=>console.error(`WhatsApp Web startup: ${e.message}`));});
